# Generated by Django 4.1.5 on 2023-01-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enr_cons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Participant',
        ),
    ]
