# Generated by Django 4.1.5 on 2023-01-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enr_cons', '0002_rename_product_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='name',
            new_name='nom',
        ),
    ]
